# Generated by Django 5.1 on 2024-09-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_password_note_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='uuid',
            new_name='slug',
        ),
    ]
