# Generated by Django 5.1 on 2024-09-03 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_uuid_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
